[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
