# netlify.toml - Fixed version
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# We'll add functions later when we create them
# [functions]
#   directory = "functions"
